# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvstore.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'kvstore.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkvstore.proto\x12\x05proto\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"8\n\x0bGetResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\":\n\x0bSetResponse\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x19\n\nDelRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0b\x44\x65lResponse\x12\r\n\x05value\x18\x01 \x01(\t2\x83\x02\n\x07KVStore\x12,\n\x03Get\x12\x11.proto.GetRequest\x1a\x12.proto.GetResponse\x12,\n\x03Set\x12\x11.proto.SetRequest\x1a\x12.proto.SetResponse\x12,\n\x03\x44\x65l\x12\x11.proto.DelRequest\x1a\x12.proto.DelResponse\x12\x36\n\tStreamSet\x12\x11.proto.SetRequest\x1a\x12.proto.SetResponse(\x01\x30\x01\x12\x36\n\tStreamGet\x12\x11.proto.GetRequest\x1a\x12.proto.GetResponse(\x01\x30\x01\x42\x0eZ\x0c/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvstore_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014/proto;proto'
  _globals['_GETREQUEST']._serialized_start=24
  _globals['_GETREQUEST']._serialized_end=49
  _globals['_GETRESPONSE']._serialized_start=51
  _globals['_GETRESPONSE']._serialized_end=107
  _globals['_SETREQUEST']._serialized_start=109
  _globals['_SETREQUEST']._serialized_end=149
  _globals['_SETRESPONSE']._serialized_start=151
  _globals['_SETRESPONSE']._serialized_end=209
  _globals['_DELREQUEST']._serialized_start=211
  _globals['_DELREQUEST']._serialized_end=236
  _globals['_DELRESPONSE']._serialized_start=238
  _globals['_DELRESPONSE']._serialized_end=266
  _globals['_KVSTORE']._serialized_start=269
  _globals['_KVSTORE']._serialized_end=528
# @@protoc_insertion_point(module_scope)
