# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'proto/.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cproto/.proto\x12\x05proto\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1e\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\nDelRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0b\x44\x65lResponse\x12\r\n\x05value\x18\x01 \x01(\t2\x93\x01\n\x07KVStore\x12,\n\x03Get\x12\x11.proto.GetRequest\x1a\x12.proto.GetResponse\x12,\n\x03Set\x12\x11.proto.SetRequest\x1a\x12.proto.SetResponse\x12,\n\x03\x44\x65l\x12\x11.proto.DelRequest\x1a\x12.proto.DelResponseB\x0eZ\x0c/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014/proto;proto'
  _globals['_GETREQUEST']._serialized_start=23
  _globals['_GETREQUEST']._serialized_end=48
  _globals['_GETRESPONSE']._serialized_start=50
  _globals['_GETRESPONSE']._serialized_end=78
  _globals['_SETREQUEST']._serialized_start=80
  _globals['_SETREQUEST']._serialized_end=120
  _globals['_SETRESPONSE']._serialized_start=122
  _globals['_SETRESPONSE']._serialized_end=152
  _globals['_DELREQUEST']._serialized_start=154
  _globals['_DELREQUEST']._serialized_end=179
  _globals['_DELRESPONSE']._serialized_start=181
  _globals['_DELRESPONSE']._serialized_end=209
  _globals['_KVSTORE']._serialized_start=212
  _globals['_KVSTORE']._serialized_end=359
# @@protoc_insertion_point(module_scope)
